name: Python CI/CD

on:
  push:
    branches: [main, develop]
    tags: ['v*.*.*']
  pull_request:
    branches: [main, develop]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # prefer pyproject extras if present, otherwise fallback to requirements files
          if [ -f "pyproject.toml" ]; then
            pip install .[dev] || pip install .
          fi
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          if [ -f "dev-requirements.txt" ]; then
            pip install -r dev-requirements.txt
          fi

      - name: Lint (flake8)
        run: |
          if command -v flake8 >/dev/null 2>&1; then
            flake8 || true
          fi

      - name: Type check (mypy)
        run: |
          if command -v mypy >/dev/null 2>&1; then
            mypy || true
          fi

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          python -m pytest -q --maxfail=1 --junitxml=reports/junit.xml --cov=. --cov-report=xml:coverage.xml

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.python-version }}
          path: reports

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: Build & Publish (tags only)
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build twine
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist