# .github/workflows/test.yml
name: Tests API RAG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          
      - name: Set environment variables
        run: |
          echo "MISTRAL_API_KEY=test_key" >> $GITHUB_ENV
          echo "OPENAGENDA_API_KEY=test_key" >> $GITHUB_ENV
          
      - name: Run tests
        run: |
          poetry run pytest tests/ -v
          
      - name: Test API startup
        run: |
          timeout 30s poetry run uvicorn scripts.rag_fast_api:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -f http://localhost:8000/health || exit 1
          
      - name: Test with curl
        run: |
          curl -f http://localhost:8000/
          curl -f "http://localhost:8000/search?query=test&k=1"




